-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 13:57:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoplantacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoplantacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoplantacao` (
  `idTipoPlantacao` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `TempoGestacao` INT NOT NULL,
  PRIMARY KEY (`idTipoPlantacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`data` (
  `iddata` INT NOT NULL,
  `Dia` VARCHAR(45) NULL,
  `MES` VARCHAR(45) NULL,
  `ANO` VARCHAR(45) NULL,
  PRIMARY KEY (`iddata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sugestao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sugestao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sugestao` (
  `idSugestao` INT NOT NULL,
  `id_datainicio` INT NOT NULL,
  `id_dataFim` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(500) NULL,
  PRIMARY KEY (`idSugestao`),
  INDEX `FK_SUGESTAO_TEMPO_idx` (`id_datainicio` ASC) VISIBLE,
  INDEX `FK_Sugestao_TEMPOFIM_idx` (`id_dataFim` ASC) VISIBLE,
  CONSTRAINT `FK_SUGESTAO_TEMPO`
    FOREIGN KEY (`id_datainicio`)
    REFERENCES `mydb`.`data` (`iddata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sugestao_TEMPOFIM`
    FOREIGN KEY (`id_dataFim`)
    REFERENCES `mydb`.`data` (`iddata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plantacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plantacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plantacao` (
  `idplantacao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `id_dataIncio` INT NOT NULL,
  `id_datafim` INT NOT NULL,
  `id_tipoplantacao` INT NULL,
  PRIMARY KEY (`idplantacao`),
  INDEX `FK_PLANTACAO_USER_idx` (`id_user` ASC) VISIBLE,
  INDEX `FK_PLANTACAO_datainicio_idx` (`id_dataIncio` ASC) VISIBLE,
  INDEX `FK_PLANTACAO_datafim_idx` (`id_datafim` ASC) VISIBLE,
  INDEX `Fk_PLANTACAO_TIPO_idx` (`id_tipoplantacao` ASC) VISIBLE,
  CONSTRAINT `FK_PLANTACAO_USER`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLANTACAO_datainicio`
    FOREIGN KEY (`id_dataIncio`)
    REFERENCES `mydb`.`data` (`iddata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLANTACAO_datafim`
    FOREIGN KEY (`id_datafim`)
    REFERENCES `mydb`.`data` (`iddata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_PLANTACAO_TIPO`
    FOREIGN KEY (`id_tipoplantacao`)
    REFERENCES `mydb`.`tipoplantacao` (`idTipoPlantacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `idstock` INT NOT NULL,
  `id_plantacao` INT NOT NULL,
  `quantidadeTotal` FLOAT NOT NULL,
  PRIMARY KEY (`idstock`),
  INDEX `FK_STOCK_PLANTACAO_idx` (`id_plantacao` ASC) VISIBLE,
  CONSTRAINT `FK_STOCK_PLANTACAO`
    FOREIGN KEY (`id_plantacao`)
    REFERENCES `mydb`.`plantacao` (`idplantacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idvenda` INT NOT NULL,
  `quantidaVenda` FLOAT NOT NULL,
  `id_stock` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `Fk_Venda_STOCK_idx` (`id_stock` ASC) VISIBLE,
  CONSTRAINT `Fk_Venda_STOCK`
    FOREIGN KEY (`id_stock`)
    REFERENCES `mydb`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alerta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alerta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alerta` (
  `idAlerta` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_plantacao` INT NOT NULL,
  `data_alerta` INT NOT NULL,
  `TituloAlerta` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlerta`),
  INDEX `Fk_Alerta_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `Fk_Alerta_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_alerta_plantacao`
    FOREIGN KEY ()
    REFERENCES `mydb`.`plantacao` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
